### ISSUE TITLE
自己VPS搭建好了，如何将节点添加进去

### ISSUE THREAD

**Issue by becapital** [EtherDream/jsproxy#189]
自己VPS搭建好了节点（如：服务器IP.xip.io:8443），
如何将节点添加到主页的节点选项？
谢谢大佬一直帮助

**Comment by JimmyTinsley** [comment]
修改gh-pages分支 conf.js里面的my site部分，将        [location.host]替换为你自己的地址，然后选择当前站点就行。或者在node map里面新增一个分类也可以，自定义lable

**Comment by h5mcbox** [comment]
还是在conf.js里的位置
找到nodemap
然后在最后一个节点下边加英文逗号（没有就直接在nodemap的大括号里加）回车加
'标题': {
label: '显示标题',
lines: {
'服务器地址（：端口）': 1,
}

**Comment by becapital** [comment]
great!

**Comment by h5mcbox** [comment]
关了issue吧
closed #189
你发一下上面这句话

**Comment by becapital** [comment]
> 修改gh-pages分支 conf.js里面的my site部分，将 [location.host]替换为你自己的地址，然后选择当前站点就行。或者在node map里面新增一个分类也可以，自定义lable

按照你的修改了，出现错误：Failed to register a ServiceWorker for scope ('https://da.last.workers.dev/') with script ('https://da.last.workers.dev/sw.js'): ServiceWorker script evaluation failed

**Comment by h5mcbox** [comment]
试下我的方法

**Comment by becapital** [comment]
> 试下我的方法
> 改了

jsproxy_config({
  // 当前配置的版本（记录在日志中，用于排查问题）
  // 每次修改配置，该值需要增加，否则不会生效。
  // 默认每隔 5 分钟自动下载配置，若想立即验证，可通过隐私模式访问。
  ver: '110',

  // 通过 CDN 加速常用网站的静态资源（实验中）
  static_boost: {
    enable: true,
    ver: 62
  },

  // 节点配置
  node_map: {
    'demo-hk': {
      label: '演示服务-香港节点',
      lines: {
        // 主机:权重
        'node-aliyun-hk-1.etherdream.com:8443': 1,
        'node-aliyun-hk-2.etherdream.com:8443': 2,
      }
    },
    'demo-sg': {
      label: '演示服务-新加坡节点',
      lines: {
        'node-aliyun-sg.etherdream.com:8443': 1,
      },
    },
    'mysite': {
      label: '当前站点',
      lines: {
        [location.host]: 1,
      }
    },
    // 该节点用于加载大体积的静态资源
    'cfworker': {
      label: '',
      hidden: true,
      lines: {
        // 收费版（高权重）
        'node-cfworker-2.etherdream.com': 4,

        // 免费版（低权重，分摊一些成本）
        // 每个账号每天 10 万次免费请求，但有频率限制
        'b.007.workers.dev': 1,
        'b.hehe.workers.dev': 1,
        'b.lulu.workers.dev': 1,
        'b.jsproxy.workers.dev': 1,
      }
    }
  },

  /**
   * 默认节点
   */
  node_default: 'mysite',
  // node_default: /jsproxy-demo\.\w+$/.test(location.host) ? 'demo-hk' : 'mysite',

  /**
   * 加速节点
   */
  node_acc: 'cfworker',

  /**
   * 静态资源 CDN 地址
   * 用于加速 `assets` 目录中的资源访问
   */
  // assets_cdn: 'https://cdn.jsdelivr.net/gh/zjcqoo/zjcqoo.github.io@master/assets/',

  // 本地测试时打开，否则访问的是线上的
  assets_cdn: 'assets/',

  // 首页路径
  index_path: 'index_v3.html',

  // 支持 CORS 的站点列表（实验中...）
  direct_host_list: 'cors_v1.txt',

  /**
   * 自定义注入页面的 HTML
   */
  inject_html: '',

  /**
   * URL 自定义处理（设计中）
   */
  url_handler: {
    'https://www.baidu.com/img/baidu_resultlogo@2.png': {
      replace: 'https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_92x30dp.png'
    },
    'https://www.pornhub.com/': {
      redir: 'https://php.net/'
    },
    'http://haha.com/': {
      content: 'Hello World'
    },
  }
})
========================================
以上是原文，我节点是：  10.62.225.33.nip.io:8443
麻烦修改好，贴上来吧，小白啊。谢谢

**Comment by h5mcbox** [comment]
jsproxy_config({
// 当前配置的版本（记录在日志中，用于排查问题）
// 每次修改配置，该值需要增加，否则不会生效。
// 默认每隔 5 分钟自动下载配置，若想立即验证，可通过隐私模式访问。
ver: '110',

// 通过 CDN 加速常用网站的静态资源（实验中）
static_boost: {
enable: true,
ver: 62
},

// 节点配置
node_map: {
'node1': {
label: '10.62.225.33节点',
lines: {
'10.62.225.33.nip.io:8443': 1,
}
},
// 该节点用于加载大体积的静态资源
'cfworker': {
label: '',
hidden: true,
lines: {
// 收费版（高权重）
'node-cfworker-2.etherdream.com': 4,

    // 免费版（低权重，分摊一些成本）
    // 每个账号每天 10 万次免费请求，但有频率限制
    'b.007.workers.dev': 1,
    'b.hehe.workers.dev': 1,
    'b.lulu.workers.dev': 1,
    'b.jsproxy.workers.dev': 1,
  }
}
},

/**

默认节点
*/
node_default: 'mysite',
// node_default: /jsproxy-demo.\w+$/.test(location.host) ? 'demo-hk' : 'mysite',
/**

加速节点
*/
node_acc: 'cfworker',
/**

静态资源 CDN 地址
用于加速 assets 目录中的资源访问
*/
// assets_cdn: 'https://cdn.jsdelivr.net/gh/zjcqoo/zjcqoo.github.io@master/assets/',
// 本地测试时打开，否则访问的是线上的
assets_cdn: 'assets/',

// 首页路径
index_path: 'index_v3.html',

// 支持 CORS 的站点列表（实验中...）
direct_host_list: 'cors_v1.txt',

/**

自定义注入页面的 HTML
*/
inject_html: '',
/**

URL 自定义处理（设计中）
*/
url_handler: {
'https://www.baidu.com/img/baidu_resultlogo@2.png': {
replace: 'https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_92x30dp.png'
},
'https://www.pornhub.com/': {
redir: 'https://php.net/'
},
'http://haha.com/': {
content: 'Hello World'
},
}
})

**Comment by becapital** [comment]
> jsproxy_config({
> // 当前配置的版本（记录在日志中，用于排查问题）
> // 每次修改配置，该值需要增加，否则不会生效。
> // 默认每隔 5 分钟自动下载配置，若想立即验证，可通过隐私模式访问。
> ver: '111',
> 
> // 通过 CDN 加速常用网站的静态资源（实验中）
> static_boost: {
> enable: true,
> ver: 62
> },
> 
> // 节点配置
> node_map: {
> 'node1': {
> label: '10.62.225.33节点',
> lines: {
> '10.62.225.33.nip.io:8443': 1,
> }
> },
> // 该节点用于加载大体积的静态资源
> 'cfworker': {
> label: '',
> hidden: true,
> lines: {
> // 收费版（高权重）
> 'node-cfworker-2.etherdream.com': 4,
> 
> ```
> // 免费版（低权重，分摊一些成本）
> // 每个账号每天 10 万次免费请求，但有频率限制
> 'b.007.workers.dev': 1,
> 'b.hehe.workers.dev': 1,
> 'b.lulu.workers.dev': 1,
> 'b.jsproxy.workers.dev': 1,
> ```
> 
> }
> }
> },
> 
> /**
> 
> 默认节点
> _/ node_default: 'mysite', // node_default: /jsproxy-demo.\w+$/.test(location.host) ? 'demo-hk' : 'mysite', /_*
> 
> 加速节点
> _/ node_acc: 'cfworker', /_*
> 
> 静态资源 CDN 地址
> 用于加速 assets 目录中的资源访问
> */
> // assets_cdn: 'https://cdn.jsdelivr.net/gh/zjcqoo/zjcqoo.github.io@master/assets/',
> // 本地测试时打开，否则访问的是线上的
> assets_cdn: 'assets/',
> 
> // 首页路径
> index_path: 'index_v3.html',
> 
> // 支持 CORS 的站点列表（实验中...）
> direct_host_list: 'cors_v1.txt',
> 
> /**
> 
> 自定义注入页面的 HTML
> _/ inject_html: '', /_*
> 
> URL 自定义处理（设计中）
> _/ //以下代码会让百度变logo pornhub重定向到php.net haha只显示hello world 直接注释 /_
> url_handler: {
> 'https://www.baidu.com/img/baidu_resultlogo@2.png': {
> replace: 'https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_92x30dp.png'
> },
> 'https://www.pornhub.com/': {
> redir: 'https://php.net/' //重定向到php.net
> },
> 'http://haha.com/': {
> content: 'Hello World'//只显示hello world
> },
> }
> */
> })

你方法，可以进入主页，但是点击图标网站，出现
前端脚本错误
TypeError: s[o] is not iterable
    at r (https://da.goshare.workers.dev/assets/bundle.c33e24c5.js:1:10944)
    at Object.m (https://da.goshare.workers.dev/assets/bundle.c33e24c5.js:1:11158)
    at M (https://da.goshare.workers.dev/assets/bundle.c33e24c5.js:1:130257)
    at async aa (https://da.goshare.workers.dev/assets/bundle.c33e24c5.js:1:133559)
    at async oa (https://da.goshare.workers.dev/assets/bundle.c33e24c5.js:1:135164)

**Comment by becapital** [comment]
出现错误：当前域名不在服务器外链白名单

**Comment by becapital** [comment]
何解？ 
### **出现错误：当前域名不在服务器外链白名单**

**Comment by h5mcbox** [comment]
{
	// 当前配置的版本（记录在日志中，用于排查问题）
	// 每次修改配置，该值需要增加，否则不会生效。
	// 默认每隔 5 分钟自动下载配置，若想立即验证，可通过隐私模式访问。
	ver: '111',

	// 通过 CDN 加速常用网站的静态资源（实验中）
	static_boost: {
		enable: true,
		ver: 62
	},

	//
	'mysite': {
		label: '自建节点',
		lines: {
			'10.62.225.33.nip.io:8443': 1,
		}
	},
	// 该节点用于加载大体积的静态资源
	'cfworker': {
		label: '隐藏节点',
		lines: {
			// 收费版（高权重）
			'node-cfworker-2.etherdream.com': 4,

			// 免费版（低权重，分摊一些成本）
			// 每个账号每天 10 万次免费请求，但有频率限制
			'b.007.workers.dev': 1,
			'b.hehe.workers.dev': 1,
			'b.lulu.workers.dev': 1,
			'b.jsproxy.workers.dev': 1,
		}
	}
},

/**
 * 默认节点
 */
node_default: 'mysite',
	// node_default: /jsproxy-demo\.\w+$/.test(location.host) ? 'demo-hk' : 'mysite',

	/**
	 * 加速节点
	 */
	node_acc: 'cfworker',

	/**
	 * 静态资源 CDN 地址
	 * 用于加速 `assets` 目录中的资源访问
	 */
	// assets_cdn: 'https://cdn.jsdelivr.net/gh/zjcqoo/zjcqoo.github.io@master/assets/',

	// 本地测试时打开，否则访问的是线上的
	assets_cdn: 'assets/',

	// 首页路径
	index_path: 'index_v3.html',

	// 支持 CORS 的站点列表（实验中...）
	direct_host_list: 'cors_v1.txt',

	/**
	 * 自定义注入页面的 HTML
	 */
	inject_html: '',

	/**
	 * URL 自定义处理（设计中）
	 */
	url_handler: {
		/*
		'https://www.baidu.com/img/baidu_resultlogo@2.png': {
			replace: 'https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_92x30dp.png'
		},
		'https://www.pornhub.com/': {
			redir: 'https://php.net/'
		},
		'http://haha.com/': {
			content: 'Hello World'
		},
	}
	*/
	}


如果还是报域名白名单则问etherdream吧
我无解

**Comment by becapital** [comment]
> https://paste.to/cn/raw/5dc00cd2c2414
> 如果还是报域名白名单则问etherdream吧
> 我无解

老师，还是不行呢，把你的全部复制进去了

**Comment by becapital** [comment]
![捕获](https://user-images.githubusercontent.com/26474009/68129965-7dd62500-ff55-11e9-9443-b234de94da44.PNG)
我修改的图标，哈哈

**Comment by h5mcbox** [comment]
@EtherDream 怎么办？

**Comment by lbgitjp** [comment]
感觉应该修改的是你部署的节点上 **( 10.62.225.33.nip.io)** 的配置文件 **allowed-sites.conf** 才行, 

把最后一行的#去掉应该就可以,
`# ~(.*)                             '$1';`
改为
`~(.*)                             '$1';`

或者增加下面两行允许 workers.dev 所有子站点

```
# ~ 开头为正则匹配，此处允许 workers.dev 所有子站点
~^https://([\w-]+)\.workers\.dev$   'wd-$1';
```

**Comment by becapital** [comment]
谢谢，按照你说的2个方法，要么：不在外链白名单，要么：LOAD FAIL

**Comment by zhbqiang** [comment]
托你的福，看到pornhub的网站就点进去了
