### ISSUE TITLE
TypeError: Cannot read property 'node_map' of undefined

### ISSUE THREAD

**Issue by czpwpq** [EtherDream/jsproxy#44]
经常会出现以下报错，包括官方DEMO
TypeError: Cannot read property 'node_map' of undefined
    at r (https://cdn.jsdelivr.net/gh/zjcqoo/zjcqoo.github.io@master/assets/bundle.4386e2f9.js:1:5762)
    at Object.u (https://cdn.jsdelivr.net/gh/zjcqoo/zjcqoo.github.io@master/assets/bundle.4386e2f9.js:1:5865)
    at f (https://cdn.jsdelivr.net/gh/zjcqoo/zjcqoo.github.io@master/assets/bundle.4386e2f9.js:1:115272)
    at I (https://cdn.jsdelivr.net/gh/zjcqoo/zjcqoo.github.io@master/assets/bundle.4386e2f9.js:1:118008)
    at C (https://cdn.jsdelivr.net/gh/zjcqoo/zjcqoo.github.io@master/assets/bundle.4386e2f9.js:1:118984)
    at https://cdn.jsdelivr.net/gh/zjcqoo/zjcqoo.github.io@master/assets/bundle.4386e2f9.js:1:119324
    at https://cdn.jsdelivr.net/gh/zjcqoo/zjcqoo.github.io@master/assets/bundle.4386e2f9.js:1:119352

**Comment by EtherDream** [comment]
清理下缓存应该就好了，最近改动比较大。（可以只清当前站点，console Application -> CLear storage）

**Comment by czpwpq** [comment]
是滴，清缓存没用，我试过了~

**Comment by EtherDream** [comment]
> 是滴，清缓存没用，我试过了~

刚刚修复了~  这问题得页面几分钟没有加载资源才会出现。。。

**Comment by czpwpq** [comment]
TypeError: Cannot read property 'has' of undefined
    at f (https://cdn.jsdelivr.net/gh/zjcqoo/zjcqoo.github.io@master/assets/bundle.176d9e8e.js:1:114074)
    at C (https://cdn.jsdelivr.net/gh/zjcqoo/zjcqoo.github.io@master/assets/bundle.176d9e8e.js:1:117805)
    at I (https://cdn.jsdelivr.net/gh/zjcqoo/zjcqoo.github.io@master/assets/bundle.176d9e8e.js:1:118781)
    at https://cdn.jsdelivr.net/gh/zjcqoo/zjcqoo.github.io@master/assets/bundle.176d9e8e.js:1:119121
    at https://cdn.jsdelivr.net/gh/zjcqoo/zjcqoo.github.io@master/assets/bundle.176d9e8e.js:1:119149
更新后，打开页面能正常访问，关闭整站后10几分钟后问题再现，再次清缓存后又能正常打开了

**Comment by EtherDream** [comment]
现在应该好了吧

**Comment by czpwpq** [comment]
嗯，测试了大半天，没什么问题了

**Comment by qwqdanchun** [comment]
想知道修复的哪里，我看了这个之后发现我这里也有这个问题

**Comment by EtherDream** [comment]
> 想知道修复的哪里，我看了这个之后发现我这里也有这个问题

前端的 sw.js 更新下就好了
